# docker-compose.yml file for local development testing
services:
  replay-sanitizer:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      # Mount the entire directory for development with live reloading
      - .:/usr/share/nginx/html:ro
